CREATE TABLE "brands" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"from_name" text NOT NULL,
	"from_email" text NOT NULL,
	"to_email" text NOT NULL,
	"smtp_provider" text NOT NULL,
	"smtp_region" text,
	"smtp_access_key" text,
	"smtp_secret_key" text,
	"smtp_host" text,
	"smtp_port" integer,
	"smtp_ssl" text,
	"smtp_username" text,
	"smtp_password" text,
	"smtp_type" text,
	"smtp_limit_hourly" integer,
	"smtp_limit_daily" integer,
	"smtp_limit_monthly" integer,
	"track_opening" text,
	"track_clicks" text,
	"max_bounce" integer,
	"gdpr" text DEFAULT 'no',
	"created_at" timestamp DEFAULT now()
);
