import { pgTable,varchar,serial, text, integer, timestamp } from 'drizzle-orm/pg-core';
export const brands = pgTable('brands', {
  id: serial('id').primaryKey(),
  name: varchar('name', { length: 50 }).notNull(),
  description: varchar('description', { length: 200 }),
  fromName: varchar('from_name', { length: 30 }).notNull(),
  fromEmail: varchar('from_email', { length: 200 }).notNull(),
  toEmail: varchar('to_email', { length: 200 }).notNull(),
  smtpProvider: text('smtp_provider').notNull(),
  smtpRegion: text('smtp_region'),
  smtpAccessKey: varchar('smtp_access_key', { length: 100 }),
  smtpSecretKey: varchar('smtp_secret_key', { length: 100 }),
  smtpHost: varchar('smtp_host', { length: 50 }),
  smtpUsername: varchar('smtp_username', { length: 50 }),
  smtpPassword: varchar('smtp_password', { length: 50 }),
  smtpType: text('smtp_type'),
  smtpPort: integer('smtp_port'),
  smtpLimitHourly: integer('smtp_limit_hourly'),
  smtpLimitDaily: integer('smtp_limit_daily'),
  smtpLimitMonthly: integer('smtp_limit_monthly'),
  maxBounce: integer('max_bounce'),
  trackOpening: text('track_opening'),
  trackClicks: text('track_clicks'),
  gdpr: text('gdpr').default('no'),
  createdAt: timestamp('created_at').defaultNow(),
});
